# Generated by Django 3.1.6 on 2021-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_match_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kick_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
