# Generated by Django 3.1.6 on 2021-02-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_kick_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_goals',
            field=models.IntegerField(null=True),
        ),
    ]
