# Generated by Django 3.1.6 on 2021-02-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210201_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
