# Generated by Django 3.1.6 on 2021-02-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210201_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assists', to='core.match'),
        ),
        migrations.AlterField(
            model_name='assist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assists', to='core.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='core.match'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='core.player'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.team')),
            ],
        ),
    ]
